# Generated by Django 4.2.24 on 2025-09-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name="farm",
            old_name="size_in_hectares",
            new_name="area_ha",
        ),
        migrations.RenameField(
            model_name="farm",
            old_name="location",
            new_name="centroid_point",
        ),
        migrations.RenameField(
            model_name="farm",
            old_name="owner",
            new_name="farmer",
        ),
        migrations.RemoveField(
            model_name="farm",
            name="name",
        ),
        migrations.AddField(
            model_name="farm",
            name="photos",
            field=models.ImageField(blank=True, null=True, upload_to="farm_photos/"),
        ),
        migrations.AddField(
            model_name="farm",
            name="polygon_geom",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="primary_crop",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="secondary_crop",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
