# Generated by Django 4.2.24 on 2025-09-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0002_crop_rename_size_in_hectares_farm_area_ha_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="primary_crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_crop_farms",
                to="farms.crop",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="secondary_crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_crop_farms",
                to="farms.crop",
            ),
        ),
    ]
