# Generated by Django 4.2.24 on 2025-09-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0003_alter_farm_primary_crop_alter_farm_secondary_crop"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="latitude",
            field=models.FloatField(default=1111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farm",
            name="longitude",
            field=models.FloatField(default=111),
            preserve_default=False,
        ),
    ]
